"""
Curated IT knowledge chunks for the local SQLite RAG store (education / reference).
Each item is indexed as one retrieval unit (title + category + body).
"""

from __future__ import annotations

# (title, category, body, source)
IT_DOCUMENTS: list[tuple[str, str, str, str]] = [
    (
        "OSI model overview",
        "Networking",
        "The OSI model has seven layers: physical, data link, network, transport, session, presentation, and application. TCP/IP maps roughly to link, internet, transport, and application. Understanding layers helps debug where failures occur (cable vs DNS vs TLS).",
        "curated",
    ),
    (
        "TCP vs UDP",
        "Networking",
        "TCP provides reliable, ordered delivery with congestion control; UDP is connectionless and best-effort. Use TCP for web, email, and file transfer when correctness matters; use UDP for latency-sensitive media or DNS queries where small loss is acceptable.",
        "curated",
    ),
    (
        "DNS basics",
        "Networking",
        "DNS maps human-readable names to IP addresses via hierarchical resolution (root → TLD → authoritative). Caching at resolvers reduces load. DNSSEC adds cryptographic authentication of records to mitigate spoofing.",
        "curated",
    ),
    (
        "HTTP and HTTPS",
        "Web",
        "HTTP is a stateless request/response protocol. HTTPS wraps HTTP in TLS, providing confidentiality and integrity. Modern sites should use HTTPS everywhere; HSTS can reduce downgrade attacks.",
        "curated",
    ),
    (
        "REST API design",
        "Web",
        "REST uses resources identified by URLs and standard verbs (GET, POST, PUT, PATCH, DELETE). Good APIs use consistent naming, pagination, idempotency for PUT/DELETE, and meaningful HTTP status codes.",
        "curated",
    ),
    (
        "JSON and serialization",
        "Web",
        "JSON is a lightweight text format for structured data, widely used in APIs. Validate inputs on the server; never trust client-supplied data for security decisions without checks.",
        "curated",
    ),
    (
        "Load balancing",
        "Infrastructure",
        "Load balancers distribute traffic across servers for scale and availability. Health checks remove failed backends. Session stickiness vs stateless design is a common architectural trade-off.",
        "curated",
    ),
    (
        "Caching layers",
        "Infrastructure",
        "Caches reduce latency and cost (CDN, reverse proxy, in-memory stores like Redis). Cache invalidation is hard: use TTLs, versioning, or event-driven purges. Stale data is a common bug source.",
        "curated",
    ),
    (
        "Virtualization vs containers",
        "Infrastructure",
        "VMs virtualize hardware; containers share the host kernel and isolate processes with namespaces/cgroups. Containers are lighter and faster to start; VMs provide stronger isolation boundaries for untrusted workloads.",
        "curated",
    ),
    (
        "Kubernetes basics",
        "Infrastructure",
        "Kubernetes orchestrates container deployment, scaling, and networking. Pods are the smallest deployable units; Services provide stable networking; Deployments manage rollouts and rollbacks.",
        "curated",
    ),
    (
        "Linux file permissions",
        "Operating Systems",
        "Unix permissions use owner/group/other with read/write/execute bits. chmod changes mode; chown changes ownership. ACLs extend fine-grained control beyond classic rwx.",
        "curated",
    ),
    (
        "Processes and threads",
        "Operating Systems",
        "A process has its own memory space; threads share memory within a process. Context switching has cost; race conditions require synchronization primitives (mutexes, semaphores).",
        "curated",
    ),
    (
        "Memory: stack vs heap",
        "Operating Systems",
        "Stack frames hold local variables and call chains; heap holds dynamic allocations. Stack overflow and heap fragmentation are distinct failure modes; garbage-collected languages reduce some heap errors.",
        "curated",
    ),
    (
        "Symmetric vs asymmetric encryption",
        "Security",
        "Symmetric keys encrypt bulk data quickly; asymmetric (public-key) crypto solves key distribution and signatures. TLS uses hybrid schemes: handshake with asymmetric, bulk data with symmetric session keys.",
        "curated",
    ),
    (
        "Hashing vs encryption",
        "Security",
        "Hashing is one-way (integrity checks, passwords with salt); encryption is reversible with the key. Never store passwords in plaintext; use slow password hashes (Argon2, bcrypt).",
        "curated",
    ),
    (
        "OWASP Top 10 (conceptual)",
        "Security",
        "Common web risks include injection, broken authentication, sensitive data exposure, XXE, broken access control, misconfiguration, XSS, insecure deserialization, using components with known vulnerabilities, and insufficient logging.",
        "curated",
    ),
    (
        "Zero trust networking",
        "Security",
        "Zero trust assumes no implicit trust inside the perimeter. Every request is authenticated and authorized; micro-segmentation limits lateral movement. Identity is the new perimeter.",
        "curated",
    ),
    (
        "SQL injection mitigation",
        "Security",
        "Use parameterized queries/prepared statements; never concatenate user input into SQL. ORMs help but can still be misused. Principle of least privilege for DB accounts limits blast radius.",
        "curated",
    ),
    (
        "Relational database design",
        "Databases",
        "Normalize to reduce redundancy; use keys and constraints for integrity. Indexes speed reads but slow writes and consume space. Transactions provide ACID guarantees when properly scoped.",
        "curated",
    ),
    (
        "ACID properties",
        "Databases",
        "Atomicity (all-or-nothing), Consistency (valid states), Isolation (concurrent transactions), Durability (committed data survives crashes). Different isolation levels trade consistency vs performance.",
        "curated",
    ),
    (
        "NoSQL trade-offs",
        "Databases",
        "Document, key-value, wide-column, and graph stores optimize for different access patterns. CAP theorem reminds you that during partitions you often choose between consistency and availability.",
        "curated",
    ),
    (
        "Backups and recovery",
        "Databases",
        "Test restores regularly; backups that are never restored are guesses. RPO/RTO define acceptable data loss and downtime. Off-site and immutable backups help against ransomware.",
        "curated",
    ),
    (
        "Git workflows",
        "DevOps",
        "Branches isolate work; merge/rebase integrate history. Pull requests enable review. Tags mark releases. `.gitignore` keeps generated files out of history.",
        "curated",
    ),
    (
        "CI/CD pipelines",
        "DevOps",
        "Continuous integration runs tests on each change; continuous delivery deploys automatically to staging/production with gates. Fast feedback loops catch regressions early.",
        "curated",
    ),
    (
        "Infrastructure as code",
        "DevOps",
        "Declarative templates (Terraform, CloudFormation) version infrastructure changes and enable reproducible environments. Drift detection finds manual changes that diverge from code.",
        "curated",
    ),
    (
        "Observability: logs, metrics, traces",
        "DevOps",
        "Logs are events; metrics are aggregates; traces follow requests across services. Together they shorten incident response. Structured logging aids search and correlation.",
        "curated",
    ),
    (
        "Cloud service models",
        "Cloud",
        "IaaS provides VMs and networks; PaaS abstracts runtime; SaaS delivers full applications. Shared responsibility model splits security tasks between provider and customer.",
        "curated",
    ),
    (
        "Object storage",
        "Cloud",
        "Object stores (S3-like) hold blobs with metadata; great for media and backups. Not a POSIX filesystem; list/prefix semantics differ from block storage.",
        "curated",
    ),
    (
        "IAM in cloud",
        "Cloud",
        "Identity and access management controls who can do what on which resources. Prefer roles over long-lived keys; scope policies narrowly; audit permissions periodically.",
        "curated",
    ),
    (
        "Machine learning vs rules",
        "AI/ML",
        "Classical software encodes explicit rules; ML learns patterns from data. ML needs representative data, evaluation metrics, and monitoring for drift. No free lunch: every model has assumptions.",
        "curated",
    ),
    (
        "Train/validation/test split",
        "AI/ML",
        "Hold out test data for final evaluation only; use validation for hyperparameters. Data leakage (e.g., duplicate near-copies across splits) inflates reported accuracy.",
        "curated",
    ),
    (
        "Overfitting and regularization",
        "AI/ML",
        "Models can memorize training noise. Regularization, dropout, more data, and simpler architectures reduce overfitting. Cross-validation estimates generalization better than a single split.",
        "curated",
    ),
    (
        "Embeddings in NLP",
        "AI/ML",
        "Embeddings map text to dense vectors capturing semantic similarity. They power search, clustering, and retrieval. Domain-specific fine-tuning can improve relevance.",
        "curated",
    ),
    (
        "What is RAG",
        "AI/ML",
        "Retrieval-augmented generation retrieves relevant documents before the LLM answers, grounding responses in external knowledge and reducing pure hallucination—though retrieval quality and attribution still matter.",
        "curated",
    ),
    (
        "Vector databases (concept)",
        "AI/ML",
        "Vector stores index embeddings for approximate nearest neighbor search at scale. Trade-offs include recall vs latency, freshness of index updates, and hybrid lexical+dense retrieval.",
        "curated",
    ),
    (
        "Alignment and RLHF (high level)",
        "AI/ML",
        "Post-training alignment steers models toward helpful, honest, harmless behavior using human feedback or preference optimization. It does not guarantee factual correctness without external grounding.",
        "curated",
    ),
    (
        "Hallucination in LLMs",
        "AI/ML",
        "**Hallucination** here means **confident, fluent outputs that are wrong or ungrounded**—not optical or psychiatric “hallucinations.” "
        "Causes include **lack of retrieval**, **stale or parametric “facts”** memorized from training, **prompt pressure** to sound certain, and **context length** limits that drop evidence. "
        "**RAG** reduces *pure* guessing by conditioning on retrieved text, but **wrong or empty retrieval** can still mislead the model. "
        "Other mitigations: **tool use** (lookup, compute), **explicit citations**, **verification loops**, and **human oversight** for medicine, law, safety, and finance. "
        "Distinguish from **sycophancy** (agreeing with the user) and **bias**—those are separate alignment issues that may co-occur.",
        "curated",
    ),
    (
        "API rate limiting",
        "Web",
        "Rate limits protect backends from abuse and ensure fair use. Implement with token buckets or sliding windows; return 429 with Retry-After headers when appropriate.",
        "curated",
    ),
    (
        "OAuth 2.0 idea",
        "Security",
        "OAuth delegates authorization without sharing passwords with third-party apps. OpenID Connect adds identity on top. Always validate tokens on the resource server; use PKCE for public clients.",
        "curated",
    ),
    (
        "Public key infrastructure",
        "Security",
        "Certificates bind identities to public keys, signed by trusted CAs. Chain validation and revocation (CRL/OCSP) are part of TLS trust. Let's Encrypt popularized free automated issuance.",
        "curated",
    ),
    (
        "Subnetting",
        "Networking",
        "Subnets partition IP space; CIDR notation specifies prefix length. Routing tables direct traffic between subnets. NAT maps many private addresses to fewer public IPs.",
        "curated",
    ),
    (
        "IPv6 adoption notes",
        "Networking",
        "IPv6 vastly expands address space and simplifies some routing features. Dual-stack deployments coexist with IPv4 during transition. Firewall rules must cover both families.",
        "curated",
    ),
    (
        "Ethernet and switching",
        "Networking",
        "Switches learn MAC addresses to forward frames within LANs; VLANs segment broadcast domains. Spanning tree prevents loops in redundant topologies.",
        "curated",
    ),
    (
        "Wireless security",
        "Networking",
        "Use WPA3 where possible; avoid open networks for sensitive work or use VPN. Rogue AP detection and enterprise WPA2/3 with 802.1X improve enterprise Wi‑Fi security.",
        "curated",
    ),
    (
        "PowerShell vs Bash",
        "Operating Systems",
        "Bash is common on Linux/macOS; PowerShell is object-oriented and native on Windows. Both automate tasks; quoting and path separators differ across shells.",
        "curated",
    ),
    (
        "Environment variables and secrets",
        "DevOps",
        "Environment variables configure apps without code changes. Secrets should not be committed; use vaults or managed secret stores and inject at runtime with minimal scope.",
        "curated",
    ),
    (
        "Docker images and layers",
        "Infrastructure",
        "Images are layered filesystem diffs; smaller images reduce attack surface and pull time. Multi-stage builds separate build-time dependencies from runtime images.",
        "curated",
    ),
    (
        "Microservices trade-offs",
        "Architecture",
        "Microservices enable independent scaling and teams but add network latency, distributed tracing needs, and deployment complexity. Monolith-first is valid until boundaries clarify.",
        "curated",
    ),
    (
        "Event-driven architecture",
        "Architecture",
        "Producers publish events; consumers react asynchronously. Message brokers (Kafka, RabbitMQ) decouple services. Idempotent consumers handle duplicate delivery.",
        "curated",
    ),
    (
        "CAP theorem summary",
        "Databases",
        "In the presence of a network partition, distributed systems often choose between strong consistency and high availability. Real systems pick per-operation consistency models (e.g., eventual consistency).",
        "curated",
    ),
    (
        "Indexing strategies",
        "Databases",
        "Indexes accelerate selective queries but add write overhead. Composite indexes match leftmost column ordering. Analyze query plans to avoid full table scans when possible.",
        "curated",
    ),
    (
        "Full-text search",
        "Databases",
        "Inverted indexes support keyword search; ranking may use TF-IDF or BM25. Combine with filters for structured attributes in hybrid search applications.",
        "curated",
    ),
    (
        "Disaster recovery sites",
        "Infrastructure",
        "Cold/warm/hot sites reflect how quickly standby systems can take over. Geographic redundancy protects against regional outages; replication lag affects RPO.",
        "curated",
    ),
    (
        "DDoS mitigation",
        "Security",
        "Absorb, divert, or filter attack traffic using upstream scrubbing centers and rate controls. Application-layer attacks need different defenses than volumetric floods.",
        "curated",
    ),
    (
        "Phishing awareness",
        "Security",
        "Verify sender domains, avoid clicking unexpected links, and use MFA. Security training reduces credential theft; technical controls (safe link rewriting) add defense in depth.",
        "curated",
    ),
    (
        "Patch management",
        "Security",
        "Timely patching closes known vulnerabilities. Balance speed with testing; critical CVEs may need emergency change processes. Inventory software to know what to patch.",
        "curated",
    ),
    (
        "Compliance frameworks (intro)",
        "Security",
        "Frameworks like ISO 27001, SOC 2, and sector-specific rules (HIPAA, PCI) structure controls and audits. Compliance supports trust but is not the same as absolute security.",
        "curated",
    ),
    (
        "Data minimization",
        "Security",
        "Collect and retain only data needed for purpose. Reduces breach impact and supports privacy regulations. Anonymization and pseudonymization lower risk when feasible.",
        "curated",
    ),
    (
        "Big O intuition",
        "Computer Science",
        "Big O describes growth of time/space vs input size. O(n) linear scans differ from O(log n) binary search. Choosing the right structure matters at scale.",
        "curated",
    ),
    (
        "Hash tables",
        "Computer Science",
        "Average O(1) lookup with a good hash function and load factor management. Worst-case degrades if many collisions; universal hashing and resizing strategies help.",
        "curated",
    ),
    (
        "Versioning semantic versioning",
        "DevOps",
        "SemVer MAJOR.MINOR.PATCH signals breaking vs additive vs bugfix changes. Clients can depend on compatible ranges; API versioning avoids silent breakage.",
        "curated",
    ),
    (
        "GraphQL vs REST",
        "Web",
        "GraphQL lets clients request shaped data in one round trip; complexity and caching differ from REST. Rate limiting and query depth limits prevent abuse.",
        "curated",
    ),
    (
        "WebSockets",
        "Web",
        "WebSockets enable full-duplex channels over HTTP upgrade, useful for live dashboards and chat. Still need authentication, authorization, and backpressure handling.",
        "curated",
    ),
    (
        "CDN benefits",
        "Web",
        "CDNs cache static assets at edge PoPs, reducing latency and origin load. Cache keys must account for query strings and headers when content varies.",
        "curated",
    ),
    (
        "TLS handshake overview",
        "Security",
        "Client and server negotiate cipher suites, authenticate server (and optionally client), derive session keys, then encrypt application data. Certificate transparency logs help detect mis-issuance.",
        "curated",
    ),
    (
        "Firewall rules",
        "Security",
        "Stateful firewalls track connections; default-deny inbound is common for servers. Egress filtering can stop malware callbacks but must not break legitimate updates.",
        "curated",
    ),
    (
        "SIEM basics",
        "Security",
        "Security information and event management aggregates logs for detection and investigation. Correlation rules and ML assist analysts; tuning reduces false positives.",
        "curated",
    ),
    (
        "Containers and rootless",
        "Infrastructure",
        "Running containers as non-root reduces host compromise impact. User namespaces and seccomp/apparmor profiles add isolation beyond default Docker settings.",
        "curated",
    ),
    (
        "Blue/green and canary deploys",
        "DevOps",
        "Blue/green switches traffic between two identical environments; canary routes a small slice first to detect issues. Feature flags decouple release from deployment.",
        "curated",
    ),
    (
        "SLA, SLO, SLI",
        "DevOps",
        "SLI measures service behavior; SLO is a target over time; SLA is a contract with consequences. Error budgets guide how much change velocity is safe.",
        "curated",
    ),
    (
        "Entropy and randomness",
        "Security",
        "Cryptographic operations need unpredictable keys from OS CSPRNGs. `/dev/urandom` on Linux; avoid weak PRNGs for secrets. Predictable randomness breaks crypto.",
        "curated",
    ),
    (
        "Unicode and encoding",
        "Computer Science",
        "UTF-8 is dominant on the web; mojibake happens when bytes are misinterpreted. Normalize strings when comparing; be careful with collation in databases.",
        "curated",
    ),
    (
        "Floating point pitfalls",
        "Computer Science",
        "Binary floats cannot represent all decimals exactly; use decimals for money or integer minor units. Compare with tolerances in scientific code.",
        "curated",
    ),
    (
        "Concurrency vs parallelism",
        "Computer Science",
        "Concurrency structures program logic with interleaved tasks; parallelism executes multiple tasks simultaneously. Async I/O improves concurrency without extra threads.",
        "curated",
    ),
    (
        "Message queues at a glance",
        "Architecture",
        "Queues buffer work between producers and consumers, smoothing spikes. At-least-once delivery requires idempotent handlers; exactly-once is expensive and often approximated.",
        "curated",
    ),
    (
        "ETL vs ELT",
        "Data",
        "ETL transforms before load; ELT loads raw then transforms in the warehouse. Cloud warehouses often prefer ELT for flexibility and separation of storage/compute.",
        "curated",
    ),
    (
        "Data lake vs warehouse",
        "Data",
        "Lakes store raw diverse data cheaply; warehouses structure data for analytics SQL. Governance (catalogs, lineage) matters as data grows.",
        "curated",
    ),
    (
        "Reproducible builds",
        "DevOps",
        "Lock dependencies and pin base images so builds are repeatable. SBOMs list software components for vulnerability tracking.",
        "curated",
    ),
    (
        "Supply chain security",
        "Security",
        "Verify package integrity with checksums/signatures, scan dependencies, and pin versions. Compromised packages are a growing attack vector.",
        "curated",
    ),
    (
        "Prompt injection vs jailbreak",
        "AI/ML",
        "Prompt injection sneaks instructions via untrusted text blended with user content; jailbreaks coax policy violations. Defenses include isolation, tool allowlists, and monitoring—not perfect.",
        "curated",
    ),
    (
        "Evaluation metrics for classifiers",
        "AI/ML",
        "Accuracy can mislead on imbalanced data; precision, recall, F1, ROC-AUC, and calibration curves give richer views. Always align metrics with real-world costs.",
        "curated",
    ),
    (
        "Transfer learning",
        "AI/ML",
        "Start from pretrained models and fine-tune on smaller domain datasets. Saves compute and often improves data efficiency versus training from scratch.",
        "curated",
    ),
    (
        "Edge computing",
        "Cloud",
        "Processing near users reduces latency and bandwidth but complicates operations. Useful for IoT, CDNs, and real-time inference with privacy constraints.",
        "curated",
    ),
    (
        "DNS over HTTPS",
        "Networking",
        "DoH encrypts DNS queries inside HTTPS to hide metadata from local networks; it changes where trust is placed (resolver choice matters for privacy).",
        "curated",
    ),
    (
        "BGP and routing (intro)",
        "Networking",
        "BGP exchanges reachability between autonomous systems on the internet. Misconfigurations can cause large outages; RPKI helps reduce route hijacks when deployed.",
        "curated",
    ),
    (
        "SSH key management",
        "Security",
        "SSH keys authenticate servers and users without passwords. Protect private keys with passphrases and hardware tokens; rotate and remove stale authorized_keys entries.",
        "curated",
    ),
    (
        "Kerberos idea",
        "Security",
        "Kerberos uses tickets and a trusted key distribution center for mutual authentication in domains. Common in enterprise Windows environments integrated with AD.",
        "curated",
    ),
    (
        "LDAP directory services",
        "Security",
        "LDAP stores hierarchical directory information (users, groups). Often backs enterprise authentication and authorization integrations.",
        "curated",
    ),
    (
        "SNMP monitoring",
        "Networking",
        "SNMP polls devices for metrics and traps for events. Secure with SNMPv3 auth/priv; default community strings are a known risk if left unchanged.",
        "curated",
    ),
    (
        "NTP and time sync",
        "Infrastructure",
        "Accurate time matters for TLS certificate validity, distributed logs, and databases. Stratum levels describe distance from reference clocks; authenticated NTP reduces spoofing.",
        "curated",
    ),
    (
        "RAID levels summary",
        "Infrastructure",
        "RAID0 stripes for speed without redundancy; RAID1 mirrors; RAID5/6 use parity for fault tolerance with different write penalties. Not a substitute for backups.",
        "curated",
    ),
    (
        "File systems: journaling",
        "Operating Systems",
        "Journaling file systems log metadata changes before applying them, reducing corruption risk after crashes. ext4, NTFS, APFS employ journaling techniques.",
        "curated",
    ),
    (
        "Containers vs VMs isolation",
        "Infrastructure",
        "Containers share the kernel; escape to host is higher impact than process isolation alone. gVisor/Kata provide stronger isolation when needed.",
        "curated",
    ),
    (
        "Service mesh",
        "Infrastructure",
        "A mesh adds mTLS, traffic policies, and observability as a data plane sidecar (e.g., Istio, Linkerd). Centralized control planes manage configuration.",
        "curated",
    ),
    (
        "gRPC vs REST",
        "Web",
        "gRPC uses HTTP/2 and protobuf for efficient typed RPCs; great for internal services. Browser support and human debugging differ from JSON REST.",
        "curated",
    ),
    (
        "Protobuf and schema evolution",
        "Web",
        "Protobuf is compact and fast to parse; backward/forward compatible evolution requires field numbering discipline and optional fields.",
        "curated",
    ),
    (
        "Webhooks",
        "Web",
        "Webhooks push events to consumer URLs over HTTP. Verify signatures with shared secrets, handle retries idempotently, and validate timestamps to block replays.",
        "curated",
    ),
    (
        "CORS overview",
        "Web",
        "Browsers enforce same-origin policy; CORS headers allow controlled cross-origin access. Misconfigured CORS can leak data; APIs must whitelist origins intentionally.",
        "curated",
    ),
    (
        "Content Security Policy",
        "Web",
        "CSP reduces XSS impact by restricting script sources and inline execution. Start in report-only mode to tune policies without breaking sites.",
        "curated",
    ),
    (
        "SSRF attacks",
        "Security",
        "Server-side request forgery tricks servers into calling internal services. Block metadata endpoints, validate URLs, and use network segmentation for admin interfaces.",
        "curated",
    ),
    (
        "XXE prevention",
        "Security",
        "Disable external entity processing in XML parsers; use simpler formats when possible. XXE can exfiltrate files and pivot internally.",
        "curated",
    ),
    (
        "Log injection",
        "Security",
        "Untrusted data in logs can forge lines or confuse parsers. Sanitize newlines and encode; ship logs to tamper-evident storage for forensics.",
        "curated",
    ),
    (
        "Dependency confusion",
        "Security",
        "Attackers publish malicious packages with names similar to private ones. Use scoped registries, explicit upstreams, and integrity locks.",
        "curated",
    ),
    (
        "SAST and DAST",
        "Security",
        "Static analysis scans source for patterns; dynamic analysis tests running apps. Neither catches everything; combine with manual review and threat modeling.",
        "curated",
    ),
    (
        "Threat modeling STRIDE",
        "Security",
        "STRIDE categorizes Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege. Helps structure design reviews.",
        "curated",
    ),
    (
        "Privacy: GDPR principles (high level)",
        "Security",
        "Lawfulness, fairness, transparency, purpose limitation, data minimization, accuracy, storage limitation, integrity/confidentiality, accountability. Not legal advice—consult professionals.",
        "curated",
    ),
    (
        "Anonymization limits",
        "Security",
        "Anonymized datasets can sometimes be re-identified with auxiliary data. Differential privacy provides mathematical guarantees in some settings.",
        "curated",
    ),
    (
        "Homomorphic encryption (idea)",
        "Security",
        "HE allows computation on encrypted data without decrypting—powerful but expensive. Used in niche privacy-preserving analytics scenarios.",
        "curated",
    ),
    (
        "Quantum threat to crypto (awareness)",
        "Security",
        "Large quantum computers could break widely used public-key schemes; post-quantum cryptography standards are emerging. Plan long-lived data protection horizons accordingly.",
        "curated",
    ),
    (
        "Green computing",
        "Infrastructure",
        "Energy-efficient hardware, rightsizing workloads, and renewable-powered datacenters reduce carbon footprint. Cost and sustainability increasingly align.",
        "curated",
    ),
    (
        "SLA uptime percentages",
        "DevOps",
        "99.9% allows ~8.76 hours downtime/year; 99.99% allows ~52.6 minutes. More nines require more redundancy and operational maturity.",
        "curated",
    ),
    (
        "Chaos engineering",
        "DevOps",
        "Deliberately inject failures in controlled experiments to validate resilience. Start small (kill single instances) with blast radius limits and monitoring.",
        "curated",
    ),
    (
        "Feature flags",
        "DevOps",
        "Decouple deployment from release; enable gradual rollouts and quick kill switches. Avoid flag sprawl and stale flags that confuse behavior.",
        "curated",
    ),
    (
        "Distributed tracing OpenTelemetry",
        "DevOps",
        "Trace IDs correlate spans across services. OpenTelemetry standardizes instrumentation for metrics, logs, and traces with vendor-neutral exporters.",
        "curated",
    ),
    (
        "YAML gotchas",
        "DevOps",
        "YAML is readable but ambiguous (Norway problem). Quote versions; validate schemas; beware arbitrary object deserialization in unsafe parsers.",
        "curated",
    ),
    (
        "Regex performance",
        "Computer Science",
        "Catastrophic backtracking can make regexes exponential time. Prefer possessive quantifiers, atomic groups, or simpler parsers for untrusted input.",
        "curated",
    ),
    (
        "Unicode normalization in search",
        "Computer Science",
        "Visually similar strings can have different codepoint sequences; NFC/NFD normalization aids matching. Collations handle locale-specific ordering.",
        "curated",
    ),
    (
        "Bloom filters",
        "Computer Science",
        "Probabilistic membership tests with false positives but no false negatives; compact for large sets. Used in databases and networking (e.g., HBase, Chrome safe browsing).",
        "curated",
    ),
    (
        "Consistent hashing",
        "Computer Science",
        "Distributes keys across nodes with minimal reshuffling when nodes join/leave. Common in distributed caches and Dynamo-style stores.",
        "curated",
    ),
    (
        "CRDTs for collaboration",
        "Computer Science",
        "Conflict-free replicated data types merge edits without central coordination; useful for collaborative editors with offline support.",
        "curated",
    ),
    (
        "Operational transformation",
        "Computer Science",
        "Transforms concurrent edits in collaborative text systems to preserve intent. Alternative to CRDTs with different trade-offs.",
        "curated",
    ),
    (
        "GPU vs CPU for ML",
        "AI/ML",
        "GPUs excel at parallel matrix math; CPUs better for branching logic and small batches. Mixed precision training speeds models when numerically stable.",
        "curated",
    ),
    (
        "Batch vs streaming inference",
        "AI/ML",
        "Batch processes large offline datasets; streaming serves low-latency online predictions with autoscaling and queueing. Latency SLOs drive architecture.",
        "curated",
    ),
    (
        "Model cards and datasheets",
        "AI/ML",
        "Document intended use, metrics, limitations, and dataset provenance to support responsible deployment and comparisons across models.",
        "curated",
    ),
    (
        "Federated learning (idea)",
        "AI/ML",
        "Train models across decentralized data without centralizing raw data—helps privacy. Communication overhead and non-IID data are challenges.",
        "curated",
    ),
    (
        "Explainability trade-offs",
        "AI/ML",
        "SHAP/LIME approximate feature importance; interpretable models may sacrifice accuracy. Regulated domains may require human-understandable rationales.",
        "curated",
    ),
    (
        "Synthetic data",
        "AI/ML",
        "Generated data can augment training when real data is scarce or sensitive; watch for distribution shift and privacy leakage from memorization.",
        "curated",
    ),
    (
        "DNS caching and TTL",
        "Networking",
        "TTL controls how long resolvers cache records; low TTLs speed failover but increase load. Balance during migrations.",
        "curated",
    ),
    (
        "SMTP, IMAP, POP3",
        "Networking",
        "SMTP sends mail; IMAP keeps mail on server with folders; POP3 often downloads and deletes. Modern clients prefer IMAP with TLS.",
        "curated",
    ),
    (
        "SMB and file shares",
        "Networking",
        "SMB provides networked file/print services common in Windows domains. Secure with signing, encryption, and least-privilege shares.",
        "curated",
    ),
    (
        "VPN types",
        "Networking",
        "Remote-access VPNs connect users; site-to-site VPNs link networks. Split tunneling routes only some traffic through VPN—security vs bandwidth trade-off.",
        "curated",
    ),
    (
        "IPsec vs SSL VPN",
        "Networking",
        "IPsec operates at layer 3; SSL VPNs often use TLS at application layer. Policy and client support determine choice.",
        "curated",
    ),
    (
        "Network segmentation",
        "Security",
        "VLANs, firewalls, and zero-trust policies isolate sensitive systems. Lateral movement after initial compromise is harder in well-segmented networks.",
        "curated",
    ),
    (
        "Honeypots",
        "Security",
        "Decoy systems attract attackers for study and early warning. Must be isolated to avoid becoming launch points.",
        "curated",
    ),
    (
        "Incident response phases",
        "Security",
        "Preparation, detection, containment, eradication, recovery, lessons learned. Playbooks and comms plans reduce chaos during breaches.",
        "curated",
    ),
    (
        "Forensics: chain of custody",
        "Security",
        "Document evidence handling to preserve admissibility. Disk imaging, write blockers, and hashed copies support integrity proofs.",
        "curated",
    ),
    (
        "Binary exploitation basics",
        "Security",
        "Memory corruption bugs may allow code execution; mitigations include ASLR, stack canaries, NX bit, and control-flow integrity. Secure coding prevents root causes.",
        "curated",
    ),
    (
        "Secure SDLC",
        "Security",
        "Integrate security in requirements, design, coding, testing, and operations. Shift-left finds issues earlier when cheaper to fix.",
        "curated",
    ),
    # --- Student_support: common concerns for Ask AI (study skills, ethics, wellbeing framing) ---
    (
        "Stress and exam anxiety (general coping)",
        "Student_support",
        "Brief anxiety is common. Evidence-based tactics: **sleep**, spaced review, short focused sessions (Pomodoro), and **breathing** exercises. "
        "If anxiety disrupts daily life, a **counselor** or campus health service can help — not a chatbot.",
        "curated",
    ),
    (
        "Imposter syndrome in tech programs",
        "Student_support",
        "Many learners feel ‘not good enough’ despite evidence of progress. **Compare to yesterday-you**, not to everyone online. "
        "Use office hours; ask **specific** questions. Completing a RAG demo you can explain beats copying a flashy repo you cannot defend.",
        "curated",
    ),
    (
        "Academic integrity — collaboration vs copying",
        "Student_support",
        "**Discuss** concepts with classmates; **write** your own report and code contributions. "
        "Copying submissions or hiding AI use where disclosure is required can violate policy. When unsure, **ask the instructor**.",
        "curated",
    ),
    (
        "How to cite generative AI in coursework",
        "Student_support",
        "Follow your department’s style. Typically: name the **tool**, **date**, and **how** you used it (e.g., ‘draft outline’, ‘code assistance’). "
        "You remain responsible for accuracy — **verify** technical claims against sources.",
        "curated",
    ),
    (
        "Plagiarism vs paraphrasing vs quotation",
        "Student_support",
        "**Quotation** uses exact words with citation. **Paraphrasing** restates ideas in your words with citation. "
        "**Plagiarism** is presenting others’ work or words as yours. Code plagiarism includes **unattributed** copy-paste from repos.",
        "curated",
    ),
    (
        "Fear of failing or disappointing family",
        "Student_support",
        "Academic pressure is real. **Communicate** early with instructors about confusion rather than hiding struggle. "
        "Many schools offer **tutoring** and **advising**. This demo cannot change grades — it can help you **learn** concepts to perform better.",
        "curated",
    ),
    (
        "Sleep and screen time before deadlines",
        "Student_support",
        "All-nighters harm **memory consolidation**. Prefer steady progress. Dim screens at night; take breaks to reduce eye strain and errors in code.",
        "curated",
    ),
    (
        "Asking for deadline extensions professionally",
        "Student_support",
        "Email **early**, be **brief**, propose a plan, attach **documentation** if relevant (medical, not casual). "
        "Policies vary; only your instructor can approve extensions — not this app.",
        "curated",
    ),
    (
        "English confidence in technical writing",
        "Student_support",
        "Clarity beats fancy words. Use **short sentences**, define acronyms once, and run a **spell-check**. "
        "Many graders value clear structure (intro, method, results, limits) over perfect idiom.",
        "curated",
    ),
    (
        "Presentation anxiety for demos",
        "Student_support",
        "Rehearse **twice** with a timer. Have a **fallback** (recorded video) if live demo fails. "
        "Explain **one** pipeline slide clearly rather than rushing ten features.",
        "curated",
    ),
    (
        "Comparing yourself to classmates online",
        "Student_support",
        "Social feeds show **highlights**, not struggle. Focus on **rubric** requirements and your **learning goals**. "
        "A minimal honest demo you understand outperforms a flashy one you cannot explain.",
        "curated",
    ),
    (
        "Ethics of using LLMs for learning",
        "Student_support",
        "LLMs can **tutor** and **brainstorm** if you **verify** outputs and follow policy. "
        "They can **hallucinate** citations and APIs — cross-check with docs. RAG systems in this course model **grounding** for that reason.",
        "curated",
    ),
    (
        "Privacy: what not to paste into class chat tools",
        "Student_support",
        "Avoid **passwords**, **tokens**, **national IDs**, **private health** details, and **employer secrets**. "
        "Use **synthetic** data in demos. If you accidentally paste a secret, **revoke** it immediately at the provider.",
        "curated",
    ),
    (
        "Understanding assignment feedback and rubrics",
        "Student_support",
        "Map each **rubric row** to a section in your report. If feedback is unclear, ask **one** targeted question in office hours. "
        "Iterate: fix the weakest rubric line first.",
        "curated",
    ),
    (
        "Team conflict — communication norms",
        "Student_support",
        "Use a **shared** doc for decisions, **date-stamped** chat for agreements, and **split** Git tasks to reduce merge pain. "
        "Escalate unresolved conflict to your instructor **before** the deadline.",
        "curated",
    ),
    (
        "Fear that AI will replace your career",
        "Student_support",
        "Roles shift toward **orchestration**, **evaluation**, and **responsible deployment** of models. "
        "Skills in **data quality**, **retrieval**, **testing**, and **ethics** remain in demand. Continuous learning is the norm in tech.",
        "curated",
    ),
    (
        "Inclusive language in technical reports",
        "Student_support",
        "Use **person-first** wording where relevant, avoid stereotypes, and describe **behavior** not assumed identity traits when discussing users or teams.",
        "curated",
    ),
    (
        "When to use campus counseling (non-crisis)",
        "Student_support",
        "Counseling can help with **stress**, **motivation**, and **adjustment** — not only crises. "
        "Services are **confidential** within legal limits; check your school’s site for appointments.",
        "curated",
    ),
    (
        "Note-taking strategies for flipped / lab courses",
        "Student_support",
        "During labs, jot **commands that worked**, **error messages**, and **one-sentence** ‘why’ for each step. "
        "That becomes your **reproducibility** section and saves panic before submission.",
        "curated",
    ),
    (
        "Balancing part-time work and study",
        "Student_support",
        "**Calendar** blocks for deep work; protect **sleep**. If work hurts grades, discuss **load** with employer or advisor — early beats late.",
        "curated",
    ),
    (
        "Dealing with harsh or vague feedback",
        "Student_support",
        "Extract **one** actionable item (e.g., ‘add evaluation metrics’). Ask **clarifying** questions politely. "
        "Separate **ego** from **artifact** — revise the work, not your self-worth.",
        "curated",
    ),
    (
        "Building confidence after a bad grade",
        "Student_support",
        "Analyze **what** lost points (concept vs presentation). Schedule **retakes** or **bonus** if offered. "
        "One grade rarely defines your trajectory — **patterns** of effort matter more.",
        "curated",
    ),
    (
        "Responsible use of Stack Overflow and GitHub",
        "Student_support",
        "**Understand** code before merging. **License** matters (copyleft vs permissive). **Attribute** snippets. "
        "For assignments, your instructor may require **original** implementation — check rules.",
        "curated",
    ),
    (
        "Neurodiversity and study systems",
        "Student_support",
        "Many students benefit from **visual** checklists, **noise-canceling**, and **predictable** routines. "
        "Formal accommodations require **official** documentation through your school’s process.",
        "curated",
    ),
    (
        "Healthy skepticism toward AI hype",
        "Student_support",
        "Not every problem needs an LLM. **Baselines** (rules, retrieval, smaller models) often win on cost and reliability. "
        "This course teaches **when** augmentation helps — see RAG vs parametric-only failures.",
        "curated",
    ),
]
